make task
urfu-2017/javascript-task-4 pull request #15
Opened 2017-10-20 21:29 UTC by Lyapa96

2017-10-20 21:29 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-10-20 21:29 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание: решено доп. задание

2017-10-31 11:41 UTC, savichev-igor requested changes
В остальном ок

🍅

2017-10-31 11:41 UTC, savichev-igor commented on .vscode/launch.json
> +{
Удали пожалуйста этот файл из PR =)

2017-10-31 11:41 UTC, savichev-igor commented on lego.js
> +            let newElement = {};
Перенос

2017-10-31 11:41 UTC, Savichev-Igor commented on lego.js
> +        return collectionCopy.map(element => {
А может через `reduce`?

2017-10-31 11:41 UTC, Savichev-Igor commented on lego.js
> +            let propertyValue = element[property];
Мне кажется, что нет смысла выносить это в переменную, если ниже она нигде не используется

2017-10-31 11:41 UTC, Savichev-Igor commented on lego.js
> +    for (let func of functions.sort(sortFunctions)) {
`forEach`?

2017-10-31 11:41 UTC, Savichev-Igor commented on lego.js
> +            return (order === 'asc') ? a[property] > b[property]
А случая с `0` нет?

2017-10-31 11:41 UTC, Savichev-Igor commented on lego.js
> +            let propertyValue = element[property];
Не понимаю смысла выносить в переменную

2017-10-31 11:47 UTC, Lyapa96 commented on .vscode/launch.json
> +{
Я эту задачу отправлял еще до первых правок, в следующей уже нет)

2017-10-31 11:51 UTC, Savichev-Igor commented on lego.js
> +    for (let func of functions.sort(sortFunctions)) {
Даже `reduce` можно

2017-10-31 11:54 UTC, Savichev-Igor commented on lego.js
> +    return arr.indexOf(elem) !== -1;
`includes`?

2017-10-31 11:55 UTC, Lyapa96 commented on lego.js
> +        return collectionCopy.map(element => {
Не понял, reduce же чтобы там сумму посчитать, не понятно, как тут его прикрутить. 
Типа аккумулирующий элемент - это новый массив?кажется это какое то извращение, либо я не понял идеи

2017-10-31 12:01 UTC, Lyapa96 commented on lego.js
> +            return (order === 'asc') ? a[property] > b[property]
Подробнее, если никакой порядок сортировки не передан? или если элементы равны?

2017-10-31 12:02 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-10-31 12:02 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание: решено доп. задание

2017-10-31 13:23 UTC, Savichev-Igor commented on lego.js
> +            return (order === 'asc') ? a[property] > b[property]
Если элементы равны

2017-10-31 13:24 UTC, Savichev-Igor commented on .vscode/launch.json
> +{
Дак ты же щас можешь из PR этот файл удалить

2017-10-31 13:33 UTC, Savichev-Igor commented on lego.js
> +        return collectionCopy.map(element => {
```
return collectionCopy.reduce(element => {
    for (len key in element) {
        if (contains(properties, key)) {
             newElement[key] = element[key];
        }
    }
}, {});
```

2017-10-31 13:38 UTC, Savichev-Igor commented on lego.js
> +            for (let key in element) {
```
return Object.keys(element).reduce((newElement, key) => {
     if (contains(properties, key)) {
         newElement[key] = element[key];
    }
}, {});
```

2017-10-31 13:40 UTC, Savichev-Igor commented on lego.js
> +        return collectionCopy.map(element => {
Ошибся строкой, я про ниже)

2017-10-31 20:29 UTC, Lyapa96 commented on .vscode/launch.json
> +{
Как то лучше не стало, может стоит вынести в функцию, но там есть дополнительные переменные, так что тоже так себе будет смотреться

2017-10-31 20:31 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 18

2017-10-31 20:32 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-10-31 20:32 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание: решено доп. задание

2017-10-31 20:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 20:40 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-10-31 20:40 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание: решено доп. задание

2017-10-31 20:49 UTC, Lyapa96 commented on lego.js
> +            return (order === 'asc') ? a[property] > b[property]
Можно так:
items.sort(function (a, b) {
  if (a.name > b.name) {
    return 1;
  }
  if (a.name < b.name) {
    return -1;
  }
  // a должно быть равным b
  return 0;
});

но корректно работает и через < или >, первый ответ с  полезностью 61
https://stackoverflow.com/questions/24080785/sorting-in-javascript-shouldnt-returning-a-boolean-be-enough-for-a-comparison

2017-11-01 13:38 UTC, Savichev-Igor commented on lego.js
> +            return (order === 'asc') ? a[property] > b[property]
Просто раньше было так, что если случая с 0 нет, то сортировка могла быть нестабильной, то есть при разных запусках одинаковые элементы могут быть переставлены, но сейчас я точно не скажу как в движках современных с этим, может уже и не актуально

2017-11-01 13:39 UTC, Savichev-Igor commented on lego.js
> +        return collection.filter(element => contains(values, element[property]));
:fire:

2017-11-01 13:39 UTC, Savichev-Igor commented on lego.js
> +            return Object.keys(element).reduce(function (newElement, key) {
Мне почему-то так сильно больше нравится, через `reduce`

2017-11-01 13:41 UTC, Savichev-Igor commented on .vscode/launch.json
> +{
???

2017-11-01 17:32 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-11-01 17:33 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание: решено доп. задание

2017-11-08 19:25 UTC, savichev-igor approved these changes

2017-11-08 19:26 UTC, Savichev-Igor commented
⭐️

2017-11-08 19:26 UTC, closed without merging