it's done
urfu-2017/javascript-task-4 pull request #22
Opened 2017-10-21 20:15 UTC by Admirallll

2017-10-21 20:16 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 18

2017-10-22 07:34 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 18

2017-10-22 07:54 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 18

2017-10-22 08:07 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 18

2017-10-22 08:09 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 15

2017-10-22 08:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 18

2017-10-22 08:15 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2017-10-22 08:43 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2017-10-22 08:45 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2017-10-22 08:47 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-10-22 08:47 UTC, honest-hrundel commented
@Vittly обрати внимание: решено доп. задание

2017-10-28 10:04 UTC, Vittly requested changes
есть вопросы и замечания
🍅

2017-10-28 10:04 UTC, Vittly commented on lego.js
> +    'filterIn': 2,
мб сначала фильтровать, а потом сортировать? типа оптимальнее будет

2017-10-28 10:04 UTC, Vittly commented on lego.js
> +    'filterIn': 2,
и почему `limit` в начале? и `format`?

2017-10-28 10:04 UTC, Vittly commented on lego.js
> +    let funcs = [...arguments].slice(1);
можно varargs исопльзовать

2017-10-28 10:04 UTC, Vittly commented on lego.js
> +    let fields = [...arguments];
varargs? `export.select = function(...fields) { ... }` ?

2017-10-28 10:04 UTC, Vittly commented on lego.js
> +                if (arg in element) {
лучше `hasOwnProperty`

2017-10-28 10:04 UTC, Vittly commented on lego.js
> +                if (arg in element) {
и лучше `arg` -> `field`

2017-10-28 10:04 UTC, Vittly commented on lego.js
> +        return collection.filter(elem => values.includes(elem[property]));
👍

2017-10-28 10:04 UTC, Vittly commented on lego.js
> +    funcs = funcs.sort((a, b) => FUNC_PRIORITETS[b.name] - FUNC_PRIORITETS[a.name]);
я бы вынес в отдельную функцию

2017-10-28 10:04 UTC, Vittly commented on lego.js
> +        return collection.map(el => {
да ладно, давай `element` или `elem`

2017-10-28 10:04 UTC, Vittly commented on lego.js
> +            return collection.filter(el => filters.some(filter => filter([el]).includes(el)));
el -> elem и можно развернуть на несколько строк, например так:

```js
return collection.filter(
    elem => filters.some(
        filter => filter([elem]).length === 1 // скажи ведь так оптимальнее!
    )
);
```

2017-10-28 10:04 UTC, Vittly commented on lego.js
> +                newCollection = filter(newCollection);
давай через `reduce`

2017-10-31 16:20 UTC, Admirallll commented on lego.js
> +    'filterIn': 2,
limit, и формат не в начале, а в конце, чем больше приоритет, тем раньше выполнится операция. А в конце они потому что так сказано в условии

2017-10-31 16:35 UTC, Admirallll commented on lego.js
> +            return collection.filter(el => filters.some(filter => filter([el]).includes(el)));
Да, с оптимальностью не поспоришь тут

2017-10-31 16:42 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-10-31 16:42 UTC, honest-hrundel commented
@Vittly обрати внимание: решено доп. задание

2017-11-01 06:40 UTC, Vittly requested changes
🍅 
почти-почти

2017-11-01 06:40 UTC, Vittly commented on lego.js
> +    'and': 10
не понимаю приоритеты. Давай разбираться:

* `format` - просто преобразует внешний вид содержимого какого-то свойства. Вроде как надо делать в конце, после `limit`-а, чтобы не форматировать свойства объектов, которые отрезали и после `select`-а, чтобы не форматировать свойства, которые отрезали. И после `filter`/`and`/`or` - зачем форматировать свойства объектов, которые отфильтровали. Плюс даже в формулировке написано "limit и format работают последними"
* `limit` как мы уже поняли выше работает до `format`-а. Еще `format` работает после `select`-а, чтобы не форматировать поля, которые не нужны и после `filterIn`/`and`/`or` - чтобы не получить неверное обрезание коллекции. Если сначала отрезать количество N, а потом сделать `filter` - может получиться меньше N. Потому что сначала мы викинули просто "хвост": не смотря на поля. А если сделать сначала `filter`, а потом `limit` мы получим не более N именно нужных нам объеков
* порядок `filterIn`/`and`/`or` и `select` из формулировки мне не понятен. Но было бы логично предположить, что фильтровать надо до `select`-а, так как это была бы скрытая зависимость. Мало ли я хочу отфильтровать друзей по определенным интересам, а потом взять их имена. Если сделаю сначала select, а потом `filter` - будет бред
* `sortBy` надо делать до `limit` - потому что от этого будет зависеть результат

Итого по порядку:
1. `filterIn` / `and` / `or`
2. `sortBy`
3. `select`
4. `limit`
5. `format`

зачем делать непоследовательные числа/приоритеты, я не понял

2017-11-01 06:40 UTC, Vittly commented on lego.js
> +    let newCollection = createObjectCopy(collection);
переменная не нужна

2017-11-01 09:24 UTC, Admirallll commented on lego.js
> +    let newCollection = createObjectCopy(collection);
ты про какую переменную?

2017-11-01 09:27 UTC, Admirallll commented on lego.js
> +    'and': 10
сейчас порядок такой же, только приоритеты в обратном порядке идут.
Приоритеты непоследовательны, чтобы в случае добавлении новой команды, можно было безболезненно добавить её в таблицу с приоритетами. А не каждый раз все сдвигать

2017-11-01 09:28 UTC, Admirallll commented
Ответил на вопросы / Задал вопросы

2017-11-02 05:16 UTC, Vittly commented on lego.js
> +    'and': 10
:) мой опыт показывает, что все соображения вида "вот это на будущее для этого не работают", когда будущее наступает что-то получается не так. А в настоящем возникают вопросы

2017-11-02 05:17 UTC, Vittly commented on lego.js
> +    'and': 10
порядок не такой, кстати - у тебя format=limit, что не оптимально, лучше format делать после limit

2017-11-02 05:18 UTC, Vittly commented on lego.js
> +    let newCollection = createObjectCopy(collection);
`newCollection` - эту, но это на мой взгляд

2017-11-02 05:18 UTC, Vittly commented on lego.js
> +    'and': 10
по идее тут можно только улучшить, а так все круто

2017-11-02 05:19 UTC, Vittly approved these changes

2017-11-02 05:19 UTC, closed without merging

2017-11-02 06:59 UTC, Admirallll commented on lego.js
> +    let newCollection = createObjectCopy(collection);
да, я тоже думал, что я всё делал аккуратно, но у меня тут есть коммит createCopy после которого прошло 5 тестов. Так что её нельзя убрать