all
urfu-2017/javascript-task-4 pull request #30
Opened 2017-10-23 12:19 UTC by ilearnf

2017-10-31 10:23 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-10-31 10:24 UTC, ilearnf commented
Прошу не засчитывать дедлайн, т. к. хрюн не пришел в первый коммит. Код с первого коммита никак не изменился.

2017-11-03 12:49 UTC, dotokoto requested changes
Привет! Посмотрела задачу, оставила замечания. Напиши мне плз в Слак, когда исправишь, чтобы я еще раз проверила

2017-11-03 12:49 UTC, dotokoto commented on lego.js
> +    FORMAT: 99
Смысл понятен, но в этой задаче точно известно, сколько всего операций. Так что можно было написать 4 (но можешь оставить и так)

2017-11-03 12:49 UTC, dotokoto commented on lego.js
> +function cloneObject(obj) {
В этой задаче, так как внутри объекта всегда примитивные значения, можно было использовать `var clonedObject = Object.assign({}, obj)`

2017-11-03 12:49 UTC, dotokoto commented on lego.js
>      exports.or = function () {
Почему у тебя звездочка выставлена в false, но методы реализовал? Они работают или нет?

2017-11-03 12:49 UTC, dotokoto commented on lego.js
> +            count = Math.min(count, collection.length);
На самом деле, это лишняя операция. `slice` сам тоже самое делает

2017-11-03 12:49 UTC, dotokoto commented on lego.js
> +                formatted.push(newItem);
Зачем пушить, если можно просто использовать `map` вместо `forEach`

2017-11-03 12:49 UTC, dotokoto commented on lego.js
> +                var newItem = Object.assign({}, item);
Нет смысла в каждом методе клонировать объекты, если ты уже склонировал вначале

2017-11-03 12:49 UTC, Dotokoto commented on lego.js
> +    var SORT_DIRECTION = {
Можно вынести в глобальные переменные, а не внутри функции определять

2017-11-03 12:49 UTC, Dotokoto commented on lego.js
> +                if (values.length === 0 || !item.hasOwnProperty(property) ||
Почему именно такие проверки? Мне кажется более логичным, если передали пустой массив или несуществующее поле, возвращать тоже пустой массив.
Типа 'Хочу получить несуществующее поле -> его нет ни в одном объекте -> все не проходят через фильтр'

2017-11-03 12:49 UTC, Dotokoto commented on lego.js
> +exports.select = select;
Почему select один вынесен отдельно, а все остальыне функции прямо в экспорте определяются?

2017-11-03 12:49 UTC, Dotokoto commented on lego.js
> +                selectedFromCollection.push(selectedItem);
Опять же, можно использовать map

2017-11-03 12:49 UTC, Dotokoto commented on lego.js
> +            var compatibleArguments = getExistingSelectArguments(
Кажется, тут ты перемудрил. Имелось в виду, что если поля нет в объекте, оно не должно добавиться после прогона через SELECT. А все объекты на существование поля проверять не нужно. Так что эта часть лишняя

2017-11-03 12:49 UTC, Dotokoto commented
И разберись, что у тебя со звездочкой. Ее не стала пока смотреть, так как выставлена в false.

2017-11-03 12:49 UTC, Dotokoto commented
🍅

2017-11-07 20:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-07 20:05 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-11-07 20:10 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-11-07 20:11 UTC, ilearnf commented on lego.js
> +function cloneObject(obj) {
согласен, перемудрил.

2017-11-07 20:18 UTC, ilearnf commented on lego.js
> +exports.select = select;
select используется в query. а вызывать его через exports.select неправильно, т. к. select может стать и неэкспортируемой.

2017-11-07 20:20 UTC, ilearnf commented on lego.js
> +                if (values.length === 0 || !item.hasOwnProperty(property) ||
поразмышлял над этим, согласен. я руководствовался тем, что из лжи следует что угодно.

2017-11-07 20:20 UTC, ilearnf commented on lego.js
> +    var SORT_DIRECTION = {
да, так лучше.

2017-11-07 20:25 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-11-07 20:25 UTC, ilearnf commented on lego.js
> +                var newItem = Object.assign({}, item);
согласен, лишнее.

2017-11-07 20:25 UTC, ilearnf commented on lego.js
> +                formatted.push(newItem);
это точно.

2017-11-07 20:26 UTC, ilearnf commented on lego.js
> +            count = Math.min(count, collection.length);
исправил.

2017-11-07 20:26 UTC, ilearnf commented on lego.js
>      exports.or = function () {
один тест не проходят, поэтому isStar == false.

2017-11-07 20:31 UTC, ilearnf commented on lego.js
> +            var compatibleArguments = getExistingSelectArguments(
это же логично, что, если поля нет в каком-то из объектов, то select из этого объекта не выберет нужного поля, и надо сругаться и/или работать с подходящими полями. это более сильное условие, чем указано в задании, но оно логично.

2017-11-07 20:32 UTC, ilearnf commented on lego.js
> +                selectedFromCollection.push(selectedItem);
да.

2017-11-07 20:37 UTC, ilearnf commented
добрый вечер, внес коррективы, спасибо!

2017-11-08 08:01 UTC, closed without merging