Вичкунина Дарья
urfu-2017/javascript-task-4 pull request #40
Opened 2017-10-24 17:45 UTC by vichkunina

2017-10-24 17:45 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 15

2017-10-24 18:05 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 15

2017-10-24 18:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-10-25 14:58 UTC, maxvipon requested changes
🍅

2017-10-25 14:58 UTC, maxvipon commented on lego.js
> +        return functionsInOrder.indexOf(a.name) <
Даша, был ли у тебя курс по теории алгоритмов?

2017-10-25 14:58 UTC, maxvipon commented on lego.js
> +    var collectionCopy = JSON.parse(JSON.stringify(collection));
используй лучше [`lodash.cloneDeep`](https://lodash.com/docs/4.17.4#cloneDeep)

2017-10-25 14:58 UTC, maxvipon commented on lego.js
> +                if (selected.indexOf(key) === -1) {
Каким методом массива тут можно заменить `indexOf`?

2017-10-25 14:58 UTC, maxvipon commented on lego.js
> +        return collection.filter(partner => values.indexOf(partner[property]) !== -1);
`indexOf` 👆

2017-10-25 14:58 UTC, maxvipon commented on lego.js
> +        return collection.filter(partner => values.indexOf(partner[property]) !== -1);
Почему ты выбрала название `partner` для этой переменной?

2017-10-29 11:48 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-11-02 04:47 UTC, maxvipon commented on lego.js
> +    if (FUNCTIONS.indexOf(a.name) > FUNCTIONS.indexOf(b.name)) {
Даша, вы же проходили уже теорию алгоритмов?

2017-11-02 04:48 UTC, maxvipon commented on lego.js
> +        return functionsInOrder.indexOf(a.name) <
Даша?

2017-11-02 04:48 UTC, maxvipon commented on lego.js
> +        return collection.filter(partner => values.indexOf(partner[property]) !== -1);
Даша?

2017-11-02 05:12 UTC, maxvipon commented
🍅
Даша, ты не ответила ни на один заданный вопрос.

2017-11-02 07:24 UTC, vichkunina commented on lego.js
> +        return functionsInOrder.indexOf(a.name) <
Здравствуйте. Да, был.

2017-11-02 07:25 UTC, vichkunina commented on lego.js
> +                if (selected.indexOf(key) === -1) {
заменила на hasOwnProperty

2017-11-02 07:33 UTC, vichkunina commented on lego.js
> +        return collection.filter(partner => values.indexOf(partner[property]) !== -1);
Фильтрация по property и values была у каждого человека в collection. Просто назвала его partner.

2017-11-02 07:58 UTC, vichkunina commented on lego.js
> +                if (selected.indexOf(key) === -1) {
а, еще inludes

2017-11-03 09:34 UTC, maxvipon commented on lego.js
> +                if (selected.indexOf(key) === -1) {
да, нужно использовать его

2017-11-03 09:35 UTC, maxvipon commented on lego.js
> +                if (selected.indexOf(key) === -1) {
> заменила на hasOwnProperty

это неверное предположение

2017-11-03 09:36 UTC, maxvipon commented on lego.js
> +        return functionsInOrder.indexOf(a.name) <
Оцени, пожалуйста, алгоритмическую сложность этой функции.

2017-11-03 10:56 UTC, vichkunina commented on lego.js
> +        return functionsInOrder.indexOf(a.name) <
O(n^2)?

2017-11-03 10:57 UTC, vichkunina commented on lego.js
> +                if (selected.indexOf(key) === -1) {
Хорошо, исправлю

2017-11-07 15:16 UTC, maxvipon commented on lego.js
> +        return functionsInOrder.indexOf(a.name) <
Сможешь оптимизировать?

2017-11-09 16:32 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-11-09 16:35 UTC, vichkunina commented on lego.js
> +        return functionsInOrder.indexOf(a.name) <
Переделала сортировку путем введения объекта FUNCTIONS, свойствами которого являются наши методы

2017-11-11 07:36 UTC, maxvipon approved these changes
🆗

2017-11-11 07:37 UTC, closed without merging