Update lego.js
urfu-2017/javascript-task-4 pull request #41
Opened 2017-10-24 18:25 UTC by Tyashentin

2017-10-24 18:25 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-10-26 07:07 UTC, VorontsovMaxim requested changes
В целом все хорошо, давай сделаем пару небольших правок и все

2017-10-26 07:07 UTC, VorontsovMaxim commented on lego.js
> +        return Object.assign({}, element);
💡 В стрелочных функциях можно сразу возвращать значение 
```js
let copiedCollection = collection.map(element => Object.assign({}, element);
```

2017-10-26 07:07 UTC, VorontsovMaxim commented on lego.js
> +                }, {});
Это можно было сделать за один `.reduce()`

2017-10-26 07:07 UTC, VorontsovMaxim commented on lego.js
> +        });
Этот код используется второй раз, имеет смысл вынести его в функцию

2017-10-26 07:08 UTC, VorontsovMaxim commented
А еще вопрос в сторону - почему ты закрыл PR с прошлой задачей, хотя там прошли все тесты и было все ок?

2017-10-26 10:24 UTC, Tyashentin commented
@VorontsovMaxim Благодарю за проверку,учёл замечания и исправил.
По поводу прошлой задачи - я решил,что будет честнее не получать балл за неё.

2017-10-27 08:08 UTC, VorontsovMaxim approved these changes

2017-10-27 08:09 UTC, VorontsovMaxim commented
Принято

2017-10-27 08:09 UTC, closed without merging