Сделал задачу
urfu-2017/javascript-task-4 pull request #42
Opened 2017-10-24 19:27 UTC by meta1-heart

2017-10-24 19:27 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-10-24 19:27 UTC, honest-hrundel commented
@Vittly обрати внимание: решено доп. задание

2017-10-28 09:51 UTC, Vittly requested changes
есть что поправить
🍅

2017-10-28 09:51 UTC, Vittly commented on lego.js
> + * @params {...methods} – Функции для запроса
не нашел в доке по jsdoc-у тэг `@params` - можешь показать?

2017-10-28 09:51 UTC, Vittly commented on lego.js
> +    for (let foo of methods.sort(sortMethods)) {
а чего не `meth` или `method` ?

2017-10-28 09:51 UTC, Vittly commented on lego.js
> +function isContain(arr, part) {
как-то не по-английски - лучше `contains`

2017-10-28 09:51 UTC, Vittly commented on lego.js
> + * @param {Array} part - часть (элемент)
эм - так элемент же? что значит часть?

2017-10-28 09:51 UTC, Vittly commented on lego.js
> +        let collectionCopy = copy(collection);
можно без переменной (вкусовщина)

2017-10-28 09:51 UTC, Vittly commented on lego.js
> +                if (isContain(properties, key)) {
хм, еще можно наоборот - идти по `properties` и делать `hasOwnProperty` - если в исходных объектах полей много, а чаще нам надо мало - так будет быстрее

2017-10-28 09:51 UTC, Vittly commented on lego.js
> +        return collection.filter(part => {
почему `part` то? почему не `elem`/`item` ?

2017-10-28 09:51 UTC, Vittly commented on lego.js
> +            let propertyName = part[property];
скорее это `propertyValue` и кмк можно без переменной

2017-10-28 09:51 UTC, Vittly commented on lego.js
> +        return collection.filter(part => {
а почему тут не делаем полную копию?

2017-10-28 09:51 UTC, Vittly commented on lego.js
> +            return (order === 'asc') ? a[property] > b[property] : b[property] > a[property];
а чего не "минусом" ? в твоем варианте будет больше сравнений вроде как

2017-10-28 09:51 UTC, Vittly commented on lego.js
> +            return (order === 'asc') ? a[property] > b[property] : b[property] > a[property];
или да, там не только числа могут быть, окей

2017-10-28 09:51 UTC, Vittly commented on lego.js
> +     * @returns {Function} оставляет элементы, пошедшие хотя бы через один фильтр
прошедшие?

2017-10-28 09:51 UTC, Vittly commented on lego.js
> +                        return true;
а давай используем `Array.prototype.some` ?

2017-10-28 09:51 UTC, Vittly commented on lego.js
> +                    if (!isPartRemainAfterFilter(part, filter)) { // элемент изчез после фильтра
а давай используем `Array.prototype.every` ?

и не чегоо и**с**чез же пишется

2017-10-28 09:53 UTC, Vittly commented on lego.js
> +    or: 1,
кстати еще вопрос - а зачем тебе приоритеты and/or?

2017-10-28 09:54 UTC, Vittly commented on lego.js
> +    or: 1,
в смысле зачем разные

2017-10-30 10:07 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-10-30 10:07 UTC, honest-hrundel commented
@Vittly обрати внимание: решено доп. задание

2017-10-30 11:49 UTC, Vittly commented on lego.js
> +function isitemRemainAfterFilter(item, filter) {
лучше `filterSingleItem`

2017-10-30 11:51 UTC, Vittly commented on lego.js
> +    return arr.indexOf(item) !== -1;
можно использовать `includes`

2017-10-30 11:52 UTC, Vittly approved these changes

2017-10-30 11:53 UTC, Vittly commented
пойдет

2017-10-30 11:53 UTC, closed without merging