первый кривой вариант
urfu-2017/javascript-task-4 pull request #45
Opened 2017-10-25 09:20 UTC by AlexBarett

2017-10-25 09:20 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 18

2017-10-25 09:54 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 18

2017-10-25 10:27 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 18

2017-10-25 11:04 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 18

2017-10-25 11:30 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 18

2017-10-25 11:37 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 18

2017-10-25 11:57 UTC, honest-hrundel commented
:tomato: Пройдено тестов 9 из 15

2017-10-25 12:31 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 18

2017-10-25 12:35 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 18

2017-10-25 12:40 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 15

2017-10-25 13:08 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-10-25 13:08 UTC, honest-hrundel commented
@eugenest обрати внимание: решено доп. задание

2017-10-28 15:02 UTC, eugenest requested changes
несколько замечаний
если что, в телеграмме я tim_evg

2017-10-28 15:02 UTC, eugenest commented on lego.js
> +    var copyCollection = [].concat(collection);
в es6 можно просто [...collection]

2017-10-28 15:02 UTC, eugenest commented on lego.js
> +    var orderedArguments = Array.from(arguments).slice(1)
можно просто указать вторым аргументом в query ...orderedArguments и обращаться к нему как к массиву

2017-10-28 15:02 UTC, eugenest commented on lego.js
> +    return orderedArguments.reduce((result, argument) => argument(result), copyCollection);
похоже, таким образом нарушается требование, что

> Фильтровать и сортировать можно по всем полям, а не только перечисленным в .select()

2017-10-28 15:02 UTC, eugenest commented on lego.js
> +
пустые строки ни к чему

2017-10-28 15:02 UTC, eugenest commented on lego.js
> +            var newPerson = Object.assign({}, person);
{...person}

2017-10-28 15:02 UTC, eugenest commented on lego.js
> +            if (person[property] !== undefined) {
для этого есть hasOwnProperty

2017-10-28 15:02 UTC, eugenest commented
🍅

2017-10-29 10:05 UTC, AlexBarett commented on lego.js
> +            var newPerson = Object.assign({}, person);
если так написать var newPerson = {...person}; или var newPerson = Object.assign({...person}); то npm выдает ошибку:109:30  error  Parsing error: Unexpected token ..

2017-10-29 10:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-29 10:08 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-10-29 10:08 UTC, honest-hrundel commented
@eugenest обрати внимание: решено доп. задание

2017-10-29 16:19 UTC, eugenest commented on lego.js
> +            var newPerson = Object.assign({}, person);
ок, оставляем
а куча ненужных пустых строк так и осталась :\

2017-10-29 16:19 UTC, closed without merging