Щукина Ирина
urfu-2017/javascript-task-4 pull request #60
Opened 2017-10-25 19:38 UTC by iriskis

2017-10-25 20:33 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-10-25 20:33 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-11-03 20:18 UTC, Mokoshka requested changes

2017-11-03 20:18 UTC, Mokoshka commented on lego.js
> +    return JSON.parse(JSON.stringify(collection));
Можно проще, используя `Object.assign`

2017-11-03 20:18 UTC, Mokoshka commented on lego.js
> +    funcs.sort((a, b) => PRIORITY[a.name] - PRIORITY[b.name]);
Непонятные названия переменных a и b

2017-11-03 20:18 UTC, Mokoshka commented on lego.js
> +        , copyCollection(collection));
Не стоит так запятые переносить, лучше ставить перенос после запятой

2017-11-03 20:18 UTC, Mokoshka commented on lego.js
> +            for (let key of Object.keys(friend)) {
Тут ведь тоже reduce можно использовать

2017-11-03 20:18 UTC, Mokoshka commented on lego.js
> +        return copyCollection(collection).sort((a, b) => {
Непонятные a и b

2017-11-03 20:18 UTC, Mokoshka commented on lego.js
> +        newCollection.forEach(friend => {
map, кажется, больше подойдет

2017-11-12 13:19 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 18 из 18

2017-11-12 13:19 UTC, honest-hrundel commented
@Mokoshka обрати внимание: решено доп. задание

2017-11-22 06:20 UTC, Mokoshka approved these changes

2017-11-22 06:20 UTC, closed without merging