сделал
urfu-2017/javascript-task-4 pull request #65
Opened 2017-10-26 00:47 UTC by HazipovVF

2017-10-26 00:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-26 00:49 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 15

2017-10-26 06:24 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-10-27 06:03 UTC, evilj0e requested changes
Поправь нейминг

2017-10-27 06:03 UTC, evilj0e commented on index.js
> -    lego.limit(4)
Не добавляй в коммит лишние файлы.

2017-10-27 06:03 UTC, evilj0e commented on lego.js
> +            obj[keys] = col[keys];
Если у тебя сложный объект, то здесь у тебя может скопироваться просто ссылка и исходный объект может мутировать.

2017-10-27 06:03 UTC, evilj0e commented on lego.js
> +    var ob = {};
Поправь нейминг

2017-10-27 06:18 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-10-27 06:29 UTC, evilj0e approved these changes

2017-10-27 06:30 UTC, closed without merging