task done without star
urfu-2017/javascript-task-4 pull request #73
Opened 2017-10-26 11:44 UTC by RomanDengin

2017-10-26 11:45 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-10-31 20:59 UTC, Grimfrid requested changes
1) а почему где-то `let` а где-то `var` по какому принципу выбираешь?
2) Для констант лучше использовать const
3) Скопировать коллекцию достаточно только в `query`
4) Лишние console.log лучше убрать
🍅

2017-10-31 20:59 UTC, Grimfrid commented on lego.js
> +function copyCollectoin(collection) {
`copyCollectoin` - опечатка

2017-10-31 20:59 UTC, Grimfrid commented on lego.js
> +            for (var value of values) {
кажется тут можно использовать Array.prototype.some

2017-10-31 20:59 UTC, Grimfrid commented on lego.js
> +            workingCollection.sort((a, b) => a[property] > b[property]);
если мне память не изменяет, функция в `sort` должна возвращать одно из: `-1`, `0`, `1`

2017-11-01 07:41 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-11-01 07:43 UTC, RomanDengin commented
🍏 
поправил замечания

2017-11-01 11:03 UTC, Grimfrid commented
Отлично!

2017-11-01 11:03 UTC, closed without merging